services:
  shopping-db:
      image: mysql:8
      # restart: always siempre reiniciará el contenedor si se detiene, lo que es útil para garantizar que la base de datos esté siempre disponible.
      restart: always
      ports:
        - "3307:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_NAME}
      volumes:
        - db_data:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
  shopping-server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - COOKIE_SECRET_KEY=${COOKIE_SECRET_KEY}
      - PORT=${PORT}
      - PUBLIC_DOMAIN_CLIENT=${PUBLIC_DOMAIN_CLIENT}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      shopping-db:
        condition: service_healthy
  shopping-client:
    build: 
      context: ./client
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - shopping-server
volumes:
  db_data:
  

